frontend-build:
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build:ci
    - npm run install:eslint
    - npm run install:prettier
    - npm run lint
    - npm run format
frontend-test:
  stage: test
  script:
    - cd frontend
    - npm install
    - npm run test:ci


