variables:
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - test

build:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script: 
    - cd frontend && docker build -t frontend . && cd ..
    - cd backend && docker build -t backend . && cd ..

test:
  image: docker:latest
  services:
    - docker:dind
  stage: test
  script:
    - cd frontend && docker run frontend
    - cd backend && docker run backend
