stages:
  - build
  - test

build:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script: 
    - echo $CI_DEPLOY_USER & echo $CI_DEPLOY_PASSWORD & echo $CI_REGISTRY
    - echo "faszomat belehúzom:)"
    # - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - cd frontend && docker build -t frontend . && cd ..
    - cd backend && docker build -t backend . && cd ..

test:
  image: docker:latest
  services:
    - docker:dind
  stage: test
  script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - cd frontend && docker run frontend
    - cd backend && docker run backend
