backend-build:
  stage: build
  script:
    - cd backend
    - npm install
    - npm run build
    - npm run lint
    - npm run format
backend-test:
  stage: test
  script:
    - cd backend
    - npm install
    - npm run test
