backend-build:
  stage: build
  script:
    - cd backend
    - npm install
    - npm run build
backend-tslint:
 stage: lint
 script:
    - npm i tslint
    - node_modules/tslint/bin/tslint .
backend-test:
  stage: test
  script:
    - cd backend
    - npm install
    - npm run test
